### ISSUE TITLE
快开学了，会更新2023的支持嘛

### ISSUE THREAD

**Issue by xiaofeiTM233** [WindLeaf233/QingJiaoHelper#4]
新的一个学年又来啦，会更新2023的支持嘛

**Comment by WindLeaf233** [comment]
现在高三了，时间少，所以之前一直都没啥更新，望见谅。

现在我们学校没搞这个答题，所以我现在没几个可以用来测试的账号，如果您有账号可以提供我会在这次周末尽量更新，谢谢。:)

（我们学校之前的账号由于我更换了电脑，相关记录没了）

**Comment by xiaofeiTM233** [comment]
2023年竞赛还没开，暂时不急，我这只能提供小学和初中的
不知道是不是学校后台还需要更新一下学生年级
我现在拿学生账号测的时候发现还是上一个学年的信息，没有自动更新到下一个学年（期末考试也显示已完成过）
然后我发现大大更了0.2.9版本了我装的还是0.2.8.1版本所以一键完成才不能用（

**Comment by WindLeaf233** [comment]
小学和初中的应该也可以，能测试就行。昨天我试了一下，对于高二目前版本的脚本似乎依旧可以使用（普通的学习和自学之类的）。由于题库还停留在 `2022` 年的问题，竞赛估计用不了。

顺带提一下，我最近在尝试用 `TypeScript` 完全重构一下，重写 UI 和一些逻辑，中秋放假那几天应该可以完成迭代到 `0.3.0` 版本。
