### ISSUE TITLE
网页已更新，脚本不能使用

### ISSUE THREAD

**Issue by andycjs** [WindLeaf233/QingJiaoHelper#5]
网页更新了，老的脚本已经不能用了，谢谢作者关注一下

**Comment by WindLeaf233** [comment]
现在高三了，时间少，所以之前一直都没啥更新，望见谅。

现在我们学校没搞这个答题，所以我现在没几个可以用来测试的账号，如果您有账号可以提供我会在这次周末尽量更新，谢谢。:)

（我们学校之前的账号由于我更换了电脑，相关记录没了）
